version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cotree-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
      - prometheus
    networks:
      - cotree-net

  redis:
    image: redis:7
    container_name: cotree-redis
    networks:
      - cotree-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1001:1001"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    networks:
      - cotree-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1001:1001"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - cotree-net

networks:
  cotree-net:
