spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//144.24.78.99:1521/FREEPDB1

  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    fail-on-missing-locations: true
    locations: classpath:db/migration

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
