spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    fail-on-missing-locations: true
    locations: classpath:db/migration

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
