spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 1800000

  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    fail-on-missing-locations: true
    locations: classpath:db/migration

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

