name: Deploy Spring Boot to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Spring Boot App
      run: ./gradlew build

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/cotree-backend
          git pull origin main

          sudo docker stop cotree-app || true
          sudo docker rm cotree-app || true
          sudo docker rmi cotree-image || true

          sudo docker build -t cotree-image .
          sudo docker run -d --name cotree-app -p 8080:8080 cotree-image
  
