name: Deploy Spring Boot + Redis + Monitoring to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e

            cd ~/cotree-backend || exit 1
            git pull origin main || exit 1

            # 🔑 application-secret.yml 복원
            echo "${{ secrets.APPLICATION_SECRET_YML }}" | base64 --decode > src/main/resources/application-secret.yml

            # 🔑 Redis 비밀번호 export
            export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}

            # 🔑 Compose down -> build -> up
            sudo docker compose down || true
            sudo docker compose build || exit 1
            sudo docker compose up -d || exit 1
          EOF
